package ui

import (
	"os"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestGameScreen_Golden(t *testing.T) {
	gs := NewGlobalScreen()
	// force transition
	s := NewStartScreen()
	s.result = &StartResult{Action: ActionNewGame}
	gs.subScreen = s
	m, _ := gs.handleStartScreenResult(s.result)
	g := m.(*GlobalScreen)
	g.completeTransition()
	w := g.subScreen.(*GameScreenWrapper)
	_, _ = w.Update(tea.WindowSizeMsg{Width: 80, Height: 24})
	out := w.View()
	if out == "" { t.Fatal("no output") }
	goldenPath := "testdata/gamescreen_golden.txt"
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		_ = os.WriteFile(goldenPath, []byte(out), 0o644)
	}
	b, err := os.ReadFile(goldenPath)
	if err != nil { t.Fatal(err) }
	if string(b) == "<golden will be generated by test>" { t.Skip("generate golden with UPDATE_GOLDEN=1") }
	if string(b) != out { t.Errorf("golden mismatch. Set UPDATE_GOLDEN=1 to update.") }
}
