package ui

import (
	"os"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestStartScreen_Golden(t *testing.T) {
	s := NewStartScreen()
	_, _ = s.Update(tea.WindowSizeMsg{Width: 80, Height: 24})
	out := s.View()
	if out == "" || out == "Loading..." { t.Fatal("no output") }
	goldenPath := "testdata/startscreen_golden.txt"
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		_ = os.WriteFile(goldenPath, []byte(out), 0o644)
	}
	b, err := os.ReadFile(goldenPath)
	if err != nil { t.Fatal(err) }
	if string(b) == "<golden will be generated by test>" { t.Skip("generate golden with UPDATE_GOLDEN=1") }
	if string(b) != out { t.Errorf("golden mismatch. Set UPDATE_GOLDEN=1 to update.") }
}
